def call(ignore_list) {
	String ignore_content = '# generated by jenkins\n'
	for(component in ignore_list){
		echo "Ignoring ${component}"
		ignore_content += "/^${component}\$/d\n"
	}
	writeFile file: 'components/encumbered/components.ignore', text: ignore_content
}
