def call(ignore_list) {
	String ignore_content = '# generated by jenkins'
	for(component in ignore_list){
		echo "Ignoring ${component}"
		ignore_content << "\n/^${component}\$/d"
	}
	writeFile file: 'components/encumbered/components.ignore', text: ignore_content
}
